module_body = ''
with open('src/collider.d.lua', encoding='utf-8') as f:
    lines = f.readlines()

i = 0
while True:
    annotations = ''
    try:
        while (line := lines[i := i + 1]).startswith('---'):
            annotations += line
    except IndexError:
        break

    if line.startswith('function Collider:'):
        module_body += annotations + line.replace('Collider:', 'module.', 1) + '\n'

with open('library/HC.lua', 'w', encoding='utf-8') as f:
    f.write('-- generated by build.py, see README.md\n\n')
    for line in lines:
        if line.strip() == '--#insert_module_body':
            f.write(module_body)
        else:
            f.write(line)